### ISSUE TITLE
Rockspec file still uses now depricated unsecure `git` connection instead of `https`; unable to install using LuaRocks

### ISSUE THREAD

**Issue by kiddigital** [axmat/lodash.lua#12]
The rockspec file contains

```
source = {
    url = "git://github.com/axmat/lodash.lua",
    tag = "v0.02",
}
```

The use of `git://` is deprecated (see [this Github blogpost](https://github.blog/2021-09-01-improving-git-protocol-security-github/))

Please replace with `https://` so it works again.

Currently trying to install lodash through LuaRocks fails on this.

**Comment by kiddigital** [comment]
@danielmgmi , @rosshadden , @axmat @nafarlee , hopefully someone can make this small update as installing Lodash via LuaRocks is now broken...

**Comment by flowyroll** [comment]
Just updated it. Hope it works now!!

**Comment by kiddigital** [comment]
@flowyroll  Thank you for updating it here. Now the new rockspec needs also being pushed/published at 'luarocks' repository.

See https://luarocks.org/modules/axmat/lodash/0.02-0

Otherwise when running `luarocks install lodash` will fetch the old rockspec (as it is now at the luarocks repo) and not the new one.

**Comment by kiddigital** [comment]
@flowyroll , can you create a v0.03-0 and upload it to the laurocks repo? The install still pulls the old 0.02.

Thank you
