### ISSUE TITLE
groupBy keys become strings; example is not reproducible

### ISSUE THREAD

**Issue by drauschenbach** [axmat/lodash.lua#5]
I'm having trouble reproducing the groupBy example:

```lua
_.print(_.groupBy({4.3, 6.1, 6.4}, function(n)
   return math.floor(n)
 end))
 --> {[4]={4.3}, [6]={6.1, 6.4}}
```

What I get instead is a result keyed by strings instead of numbers:

```bash
$ lua
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> _ = require 'lodash'
> _.print(_.groupBy({4.3, 6.1, 6.4}, function(n) return math.floor(n) end))
{["6"]={6.1, 6.4}, ["4"]={4.3}}
```

**Comment by drauschenbach** [comment]
I removed the call to `_.str()` in the groupBy function and verified that the results are now correct.

I also notice that the unit tests are asserting the wrong key datatypes, which is not consistent with the source data or the README example.

**Comment by flowyroll** [comment]
Thanks for reporting this. Would you please create a pull request with the fix?

**Comment by themadsens** [comment]
Done (#9)
